### ISSUE TITLE
[Crash]: Having issues activating on premade world

### ISSUE THREAD

**Issue by TheTrueRmanV1** [Fuzss/respawninganimals#19]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.1.1

### Notes (Required)

1. open lan screen
2. activate cheats as to be able to change game rule
3. change to lan game
4. change game rule as stated
5. no changes seem to occur in the environment
6. save and quit to menu
7. click on single player upon returning to menu
8. crash insues

### Crash Report (Required)

https://gist.github.com/TheTrueRmanV1/47c03021e66fe133f3e2c04b6ce55a9e

**Comment by TheTrueRmanV1** [comment]
Forgive me if this seems like a trivial thing like a mod conflict. i am new to using mods in gaming and have little knowledge on the topic

**Comment by Fuzss** [comment]
Your issue is caused by either wall jumping or controllable. 

To see Respawning Animals in effect when activated in an old world it‘s best to travel a little into unloaded chunks. It‘s also possible that in old chunks animals will stay around and no new ones will spawn in an effort to not break animal farms. I don‘t exactly remember how it’s implemented.

**Comment by TheTrueRmanV1** [comment]
ill give it another go without wall jump then. I grew up a console player so im too used to using a controller. thank you for your help.

**Comment by TheTrueRmanV1** [comment]
i tried exploring and im not seeing any vanilla animals show up. i do have other mob mods installed as well. im gonna disable the mod for now as im fearing any new chunks i discover may permanently have no animals in it

**Comment by TheTrueRmanV1** [comment]
and the wall jump was causing the crash. did it again with just controllable and no crash
